version: "3.8"

services:
  gin-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data/data:/var/lib/mysql
      - ./mysql_data/conf.d:/etc/mysql/conf.d # 替换为你的宿主机 MySQL 配置目录 (可选)
    restart: always
  gin-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  gin-web:
    # 使用本地的 Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    command: "/main"
    ports:
      - "8081:8081"
    depends_on:
      - gin-mysql
      - gin-redis
    restart: always

volumes:
    redis_data:
    mysql_data: